### ISSUE TITLE
ISIS is failing a topotest?

### ISSUE THREAD

**Issue by donaldsharp** [FRRouting/topotests#29]
>       assert error_logs == "", "Daemons report errors to StdErr"
E       AssertionError: Daemons report errors to StdErr
E       assert 'r1 ISISd Std...bugging is on' == ''
E         - r1 ISISd StdErr Output:
E         - 2017/08/28 12:07:22 warnings: ISIS: ISIS-Spf: TENT is empty SPF-root:robot\r
E         - 2017/08/28 12:07:22 warnings: ISIS: ISIS-Spf: TENT is empty SPF-root:robot\r
E         - 2017/08/28 12:07:22 warnings: ISIS: ISIS-Spf: TENT is empty SPF-root:robot\r
E         - 2017/08/28 12:07:22 warnings: ISIS: ISIS-Spf: TENT is empty SPF-root:robot\r
E         - IS-IS Event debugging is on

all-protocol-startup/test_all_protocol_startup.py:276: AssertionError
============== 1 failed, 68 passed, 14 skipped in 701.64 seconds ===============

**Comment by cfra** [comment]
This warning in isisd was not guarded by a debug flag. Since this warning can ocurr legitimately, particularly during startup, I have decided to guard it by a debug flag. The change do implement this for master and stable has been pushed to https://github.com/opensourcerouting/frr/tree/isisd-fix-confusion-purge and https://github.com/opensourcerouting/frr/tree/isisd-fix-confusion-purge-stable respectively. Could you or Martin verify whether this unbreaks the topotest?

**Comment by mwinter-osr** [comment]
Fixed in https://github.com/opensourcerouting/frr/tree/isisd-fix-confusion-purge-stable but still broken in https://github.com/opensourcerouting/frr/tree/isisd-fix-confusion-purge

I see the fix on the top of the -stable tree, but can't see the same fix in the other tree. Are you sure that you pushed to commit to both?
( if you are logged in to ci1.netdef.org, then you'll see the failure at https://ci1.netdef.org/browse/FRR-OSRFRR225-TOPOU1604-2 )

**Comment by cfra** [comment]
PRs merged, so closing this.
