### ISSUE TITLE
Linux kernel configuration for vpls support

### ISSUE THREAD

**Issue by beneslami** [FRRouting/topotests#78]
Hi all.
Would it be possible to add linux kernel configuration here ?
I run these commands before I run l2vpn on frr:
ip link add type bridge
ip link set dev bridge0 up                                  
ip link set dev eth0 up                                                                        
ip link set dev eth0 master bridge0                                                        
ip link add name mpw0 type dummy                                    
ip link set dev mpw0 up                                
ip link set dev mpw0 master bridge0

**Comment by rwestphal** [comment]
HI @beneslami,

As we discussed on Slack, the Linux kernel doesn't support pseudowires as of now. And since you're already using VPP, it makes more sense for you to extend the FRR FPM interface to announce MPLS labels and pseudowires and install them in the VPP data plane (which supports VPLS).

I'll close this issue now. Please don't hesitate to ask any further questions if necessary.

**Comment by vjardin6WIND** [comment]
DPDK does not scale on low end systems. It would make more sense to fix up Linux kernel first. 
There was a tentative from David and Amine but then they did move to some other topics. 

https://lwn.net/Articles/731590/
