### ISSUE TITLE
bgpd memory losses don't trigger failure

### ISSUE THREAD

**Issue by louberger** [FRRouting/topotests#87]
e.g., no error on https://ci1.netdef.org/browse/FRR-FRR-1065/artifact/TOPOI386/MemoryLeaks/memleak_bgp_l3vpn_to_bgp_vrf.test_bgp_l3vpn_to_bgp_vrf.txt

**Comment by rzalamena** [comment]
Is this still a problem?

**Comment by louberger** [comment]
I need to check...


----------

**Comment by rzalamena** [comment]
From the recent CI failures I think this has been fixed. I'll leave this issue open for another week to give people a chance to report back before closing it.

@louberger thanks for the work helping fix this!

**Comment by rzalamena** [comment]
This issue was fixed and I can see the `bgpd` failures in the logs.

Note: there were made some changes to make topotest abort with errors on `master` and newer versions and accept failures (but show them as errors) on FRR 5.0 and older.

Relevant PRs:
* https://github.com/FRRouting/topotests/pull/104
* https://github.com/FRRouting/topotests/pull/101
